language: generic
sudo: required
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=6603364284e4fe27f973e6d2e42b7eacf418baabf87b89638d46453772652d2e
    - REPO=https://github.com/beyondcoin-project/beyondcoin.git
    - COMMIT=ebdf68e6410fc419079dba7014ae75aa46ff2e36
    - TARGETHOST=aarch64-linux-android
    - BITS=64
    - REPONAME=beyondcoin
    - RENAME=beyondcoin
    - CONFIGURE=--disable-man
  matrix:
    - unused=true
    - TARGETHOST=armv7a-linux-androideabi BITS=32
    - TARGETHOST=x86_64-linux-android
    - TARGETHOST=i686-linux-android BITS=32

script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $REPONAME $RENAME $CONFIGURE $TARGETHOST $BITS"
